### ISSUE TITLE
Media query failing

### ISSUE THREAD

**Issue by chachasikes** [cagov/wordpress-to-github#42]
Got this error pulling cannabis media api data from our development site.

```
Downloading...https://dev-cagov-dcc.pantheonsite.io/wp-content/uploads/2021/08/Screen-Shot-2021-08-16-at-12.37.31-PM.png
Tree data is 1001460 bytes
Creating tree for Wordpress Media Update (776 updates) - 776/776 items
(node:24338) UnhandledPromiseRejectionWarning: Error: 500 error making request post https://api.github.com/repos/cagov/cannabis.ca.gov/git/trees: "Internal Server Error"
    at new ResponseError (/Users/chachasikes/Work/ca.gov/wordpress-to-github/node_modules/github-api/dist/components/Requestable.js:50:118)
    at handler (/Users/chachasikes/Work/ca.gov/wordpress-to-github/node_modules/github-api/dist/components/Requestable.js:379:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PrIfChanged (/Users/chachasikes/Work/ca.gov/wordpress-to-github/wordpress-to-github/gitTreeCommon/index.js:149:26)
    at async SyncEndpoint (/Users/chachasikes/Work/ca.gov/wordpress-to-github/wordpress-to-github/index.js:203:7)
    at async doProcessEndpoints (/Users/chachasikes/Work/ca.gov/wordpress-to-github/WordpressSync/index.js:44:5)
    at async module.exports (/Users/chachasikes/Work/ca.gov/wordpress-to-github/WordpressSync/index.js:28:5)
    at async /Users/chachasikes/Work/ca.gov/wordpress-to-github/WordpressSync/debug.js:10:11
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24338) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 494)
(node:24338) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by chachasikes** [comment]
Running this again. No issues with drought site, which is much smaller.

Cannabis site has a lot of media assets

**Comment by chachasikes** [comment]
Interesting observation (might be working as intended)

cannabis.ca.gov has a bunch of PDFs. There are also thumbnails for the pdfs in the different media sizes.

**Comment by chachasikes** [comment]
Also this is a fascimile site and I need to make sure the files I imported imported correctly.

**Comment by chachasikes** [comment]
Let's replay this with a perfect database & files clone.

**Comment by chachasikes** [comment]
I put a request for files - will circle back when I update the db clone

**Comment by chachasikes** [comment]
(we need the db clone of other features that are not going to be on the production site)
